sudo: required

services: 
  - docker


before_install: 
  - docker build -t hani221b/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hani221b/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-767397986486"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY" 