sudo: required

services: 
  - docker


before_install: 
  - docker build -t hani221b/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hani221b/docker-react npm run test -- --coverage