sudo: required

services: 
  - docker


before_install: 
  - docker build -t hani221b/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hani221b/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "new-docker"
  env: "New-docker-env"
  bucket_name: "new-docker"
  bucket_path: "new-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY" 